### ISSUE TITLE
Building Noodl

### ISSUE THREAD

**Issue by rvegele** [noodlapp/noodl#28]
On macOS Ventura 13.6 I had to use Node v16 to get it to build correct. 

Using Node v18 all the packages downloaded without errors, but would not run.

Perhaps it could be noted somewhere in the readme as a possible "workaround" for some in the same boat.

**Comment by erictuvesson** [comment]
Currently there is an engine lock in the package.json. I would suggest changing that to v16, because v18 is not working on that many computers.
https://github.com/noodlapp/noodl/blob/42e065b5861cf2a8844161ec50449b9291bcd417/package.json#L46-L49
